server:
  # Authorization HTTP header requires to enlarge max header size.
  max-http-header-size: 65000
  port: 8092

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false

xs2a.license.url: https://github.com/adorsys/xs2a/blob/master/LICENSE.md

xs2a:
  certificate-generator:
    template:
      public:
        key:
          "certificates/MyRootCA.key"
      private:
        key:
          "certificates/MyRootCA.pem"


# Cors configuration
management:
  endpoints:
    web:
      cors:
        allow-credentials: true
        allowed-origins: "*"
        allowed-headers: Access-Control-Allow-Headers, Content-Type, Origin, X-Requested-With, Cookie
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
        max-age: 3600
